import selectQuery from './select';
import selectPageQuery from './selectPage';
import versionQuery from './version';
import batchInsertQuery from './batchInsert';
import batchUpdateQuery from './batchUpdate';
import batchDeleteQuery from './batchDelete';
import insertOneQuery from './insertOne';
import hasChangeQuery from './hasChange';
import updateOneQuery from './updateOne';
import removeOneQuery from './removeOne';

const base = (client, tableName, exposedFields, searchableFieldsList, sortableFieldsList, idOptions = {}, extraOptions = {}) => {
    const idFieldName = idOptions.name || 'id';
    const idAutoGenerated = !!idOptions.autogenerated;

    const historyTable = extraOptions.historyTable;
    const watchedFields = extraOptions.watchedFields || exposedFields;

    const searchableFields = searchableFieldsList || exposedFields;
    const sortableFields = sortableFieldsList || exposedFields;

    const select = selectQuery(client, tableName, exposedFields, idFieldName);

    const selectPage = selectPageQuery(client, tableName, exposedFields, searchableFields, sortableFields, idOptions, extraOptions);

    const version = historyTable ? versionQuery(client, tableName, historyTable, exposedFields, idFieldName, idAutoGenerated) : null;

    const batchInsert = batchInsertQuery(client, tableName, exposedFields, idFieldName, idAutoGenerated, version);

    const batchUpdate = batchUpdateQuery(client, tableName, exposedFields, idFieldName);

    const batchDelete = batchDeleteQuery(client, tableName, exposedFields, idFieldName);

    const insertOne = insertOneQuery(client, tableName, exposedFields, idAutoGenerated, idFieldName, version);

    const hasChange = hasChangeQuery(select, watchedFields);

    const updateOne = updateOneQuery(client, tableName, exposedFields, idFieldName, idAutoGenerated, version, hasChange);

    const removeOne = removeOneQuery(client, tableName, exposedFields, idFieldName, version);

    function* exists(entityId) {
        const result = yield client.query_(`SELECT EXISTS(SELECT 1 FROM ${tableName} WHERE ${idFieldName} = $entityId)`, {entityId});

        return result.rows[0].exists;
    }

    return {
        selectAll: select.selectAll,
        selectOneById: select.selectOneById,
        countAll: select.countAll,
        refresh: select.refresh,
        selectPage,
        batchDelete,
        batchInsert,
        batchUpdate,
        insertOne,
        updateOne,
        removeOne,
        exists,
        version,
        hasChange,
    };
};

base.getFormattedDateField = function getFormattedDateField(fieldName, asName) {
    return `to_char(${fieldName} at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') as ${asName || fieldName}`;
};

export default base;
