import valueSubQuery from './valueSubQuery';

export default (client, tableName, fields, idAutoGenerated, idFieldName, version, returningFields = fields) => {
    const getValueSubQuery = valueSubQuery(fields, idAutoGenerated, idFieldName);

    return function* insertOne(data, isWhitelisted) {
        const values = getValueSubQuery(data, null, isWhitelisted);
        const query = `INSERT INTO ${tableName} (${values.columns.join(', ')}) VALUES(${values.query}) RETURNING ${returningFields.join(', ')}`;
        const entity = (yield client.query_(query, values.parameters)).rows[0];

        if (!entity) {
            throw new Error('not found');
        }

        if (version) {
            yield version(entity, 'insert', true);
        }

        return entity;
    };
};
