export default (exposedFields, idAutoGenerated, idFieldName) => {
    return function getValueSubQuery(data, suffix = '', isWhitelisted, raw) {
        const query = [];
        const parameters = {};
        const columns = [];

        const fields = (isWhitelisted ? Object.keys(data) : exposedFields);

        fields.forEach(field => {
            if (!raw && idAutoGenerated && field === idFieldName) return;
            if (!raw && typeof data[field] === 'undefined') return;
            columns.push(field);
            query.push(`$${field}${suffix}`);
            parameters[field + suffix] = data[field];
        });

        return {
            query: query.join(', '),
            parameters,
            columns,
        };
    };
};
